issueTrackerURL = "https://github.com/nexusnode/crafting-dead/issues"
license = "GPL v3.0"
loaderVersion = "[27,)"
modLoader = "javafml"

[[mods]]
authors = "Sm0keySa1m0n, Arzio"
credits = "Sm0keySa1m0n, Arzio, F3RULLO14"
description = '''
    The Minecraft zombie survival mod.
    '''
displayName = "Crafting Dead"
displayURL = "www.craftingdead.com"
modId = "craftingdead"
version = "${file.jarVersion}"

[[dependencies.craftingdead]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[35.1.7,)"
