modLoader="javafml"
loaderVersion="[27,)"
license="GPL v3.0"

[[mods]]
modId="craftingdead" 
version="${file.jarVersion}"
displayName="Crafting Dead"
description='''
The Minecraft zombie survival mod.
'''