modLoader="javafml"
loaderVersion="[27,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/nexusnode/crafting-dead/issues"

[[mods]]
modId="craftingdead" 
version="${file.jarVersion}"
displayName="Crafting Dead"
description='''
The Minecraft zombie survival mod.
'''