name: Crafting Dead

on:
  push:
    branches: [ 1.18.x ]
  pull_request:
    branches: [ 1.18.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
         ~/.gradle
         ./.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
       ./gradlew crafting-dead-core:build
       ./gradlew crafting-dead-immerse:build
       ./gradlew crafting-dead-survival:build
       ./gradlew crafting-dead-decoration:build
    - uses: actions/upload-artifact@v2
      with:
        name: crafting-dead
        path: |
          ./crafting-dead-core/build/libs/*.jar
          ./crafting-dead-immerse/build/libs/*.jar
          ./crafting-dead-survival/build/libs/*.jar
          ./crafting-dead-decoration/build/libs/*.jar
