issueTrackerURL = "https://github.com/nexusnode/crafting-dead/issues"
license = "GPL v3.0"
loaderVersion = "[27,)"
modLoader = "javafml"

[[mods]]
authors = "Sm0keySa1m0n"
credits = "Sm0keySa1m0n"
displayName = "Crafting Dead Immerse"
displayURL = "www.craftingdead.com"
modId = "craftingdeadimmerse"
version = "${file.jarVersion}"

[[mods]]
modId="clientresetpacket"
version="2.0.0"
displayName="Client Reset Packet"
displayURL="https://github.com/m1lc0lm/Forge-Client-Reset-Packet"
credits="https://github.com/EnvyWare/Forge-Client-Reset-Packet"
authors="Malcolm (m1lcolm), Just-Chaldea, EnyWare"
description='''
Adds a reset packet to Minecraft Forge to allow Modern Forge (1.13+) support on proxies.
'''

[[dependencies.craftingdeadimmerse]]
mandatory = true
modId = "craftingdead"
side = "BOTH"
versionRange = "[1.6.0-alpha,)"

[[dependencies.craftingdeadimmerse]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[40.1.80,)"
